### ISSUE TITLE
More error handling

### ISSUE THREAD

**Issue by mmattbtw** [DoobDev/Doob#125]
There is only a tiny bit of error handling, need to:
	- [ ] Add error handling for basic commands.
	- [ ] Add more advanced error handling for more advanced commands.

**Comment by AndyThePie** [comment]
Considering this is "High Priority", I doubt this should be marked stale...

**Comment by mmattbtw** [comment]
> Considering this is "High Priority", I doubt this should be marked stale...

true, but as with 3 other ones, it will automatically be marked anyways. https://github.com/DoobDev/Doob/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3A%22High+Priority%22+is%3Aclosed+label%3A%22Stale%22
