### ISSUE TITLE
Add ability to see how much exp is needed to complete a level

### ISSUE THREAD

**Issue by timothypidashev** [DoobDev/Doob#221]
would love to be able to see this

**Comment by mmattbtw** [comment]
this is the formula `(xp + xp_to_add) // 42) ** 0.55`, i can most likely do this

**Comment by timothypidashev** [comment]
would love it if you do, thankyou

**Comment by timothypidashev** [comment]
tbh i can pr it for you, but im not that good at calculus lol, and it looks like you would need to get the derivative from that formula. 
So I have a question, what is the formula based off of?

**Comment by timothypidashev** [comment]
Your level is calculated from xp as int(xp ** 0.55), if I understand it correctly. So to reach lvl, it needs to be that xp**0.55 is at least lvl. Put both sides to the power of 1/0.55, and you'll get that xp = lvl**(1/0.55)``

**Comment by AndyThePie** [comment]
Looking into this one, no promises though~

**Comment by timothypidashev** [comment]
Tysm I’m not good at math lol
