### ISSUE TITLE
Async sqlite?

### ISSUE THREAD

**Issue by timmypidashev** [DoobDev/Doob#246]
would be great to have an async db with aiosqlite or something.

**Comment by mmattbtw** [comment]
something I would have to do more research in to implement, not sure.

**Comment by mmattbtw** [comment]
I'm gonna go ahead and close this, because this would be something I would have to rewrite our entire datastructure, so I might as well just use something like https://github.com/coleifer/peewee when I eventually rewrite the bot.

**Comment by timothypidashev** [comment]
I am assuming the reopen means this pr is a go, will get to work.

**Comment by mmattbtw** [comment]
@timothypidashev All up to you, just reopened to issue and stuff to show that its getting worked on by someone

**Comment by timothypidashev** [comment]
woops, lmao accidentally hit close while scrolling, thats a first

**Comment by mmattbtw** [comment]
closing due to the upcoming v3 rewrite, all v2 issues and pull requests have been closed.
