### ISSUE TITLE
Proper mute/unmute commands 

### ISSUE THREAD

**Issue by x-daniel-17** [doobdev/doob#53]
Make the mute and unmute commands work :(

- [x] the functionality 
- [ ] per server mutes

**Comment by mmattbtw** [comment]
1. you are def working on this with me lo
2. removed v2 label, we aren't using it anymore (see #47)

**Comment by x-daniel-17** [comment]
Added v1 😎

**Comment by mmattbtw** [comment]
you are getting fired

**Comment by x-daniel-17** [comment]
no meanie :(

**Comment by mmattbtw** [comment]
ur off the payroll 🤷‍♂️

**Comment by x-daniel-17** [comment]
This is legit the most important thing

**Comment by x-daniel-17** [comment]
> ur off the payroll 🤷‍♂️

NOOOOO

**Comment by mmattbtw** [comment]
duh thats why we should work on it asap

**Comment by x-daniel-17** [comment]
Ok boomer 😎

**Comment by mmattbtw** [comment]
ok are we working on it right now or tonight, im bored @x-daniel-17

**Comment by x-daniel-17** [comment]
bye

**Comment by mmattbtw** [comment]
ok so tonight

what time?

**Comment by x-daniel-17** [comment]
When I’m back from dinner

**Comment by x-daniel-17** [comment]
Which starts later

**Comment by x-daniel-17** [comment]
So like 6:30

**Comment by mmattbtw** [comment]
timezone?

**Comment by mmattbtw** [comment]
26 days ago??? already??
