### ISSUE TITLE
Shorter cooldowns for patrons

### ISSUE THREAD

**Issue by mmattbtw** [doobdev/doob#55]
Rack in those patrons part 2 ![xqcM](https://static-cdn.jtvnw.net/emoticons/v1/1035672/1.0)

**Comment by mmattbtw** [comment]
need help >~< @x-daniel-17

**Comment by x-daniel-17** [comment]
I can help 👍

**Comment by x-daniel-17** [comment]
L8r tho™️

**Comment by mmattbtw** [comment]
i think i got it

**Comment by x-daniel-17** [comment]
o

**Comment by mmattbtw** [comment]
still want help on that mute command A.K.A. you do it for me LULW
