### ISSUE TITLE
Lack of commenting

### ISSUE THREAD

**Issue by Galactipod** [DoobDev/Doob#86]
I've only looked at a few files, but there seems to be a complete lack of commenting. You should always comment your code if it isn't very simple, especially if you expect other people to understand and contribute to it.

I know that going back and commenting all your code is a daunting task, but it's important. It might just be because I'm a beginner at Python, but I don't really understand your code. Other potential contributors might not, either.

**Comment by mmattbtw** [comment]
Will do in the next update.
